require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/no_comments/**/*'

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/no_comments/**/*'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/no_comments/no_comments_cli_spec.rb'

RSpec/NestedGroups:
  Enabled: false
